### ISSUE TITLE
Node-RED Crash

### ISSUE THREAD

**Issue by luisiam** [bmdevx/node-red-contrib-amcrest-ad110#1]
Hi, I really appreciate your work and this is working perfectly. However, it is crashing my Node-RED from time to time with the following error.

```
8 Dec 16:05:31 - [red] Uncaught Exception:                                                                                                               
8 Dec 16:05:31 - TypeError: Cannot read property 'cancel' of null                                                                                        
    at Timeout._onTimeout (/data/node_modules/amcrest-ad110/amcrest-ad110.js:141:43)                                                                     
    at listOnTimeout (internal/timers.js:554:17)                                                                                                         
    at processTimers (internal/timers.js:497:7)
```

**Comment by bmdevx** [comment]
Issue should be fixed. Pushed to npm and NodeRED flows.
